config/routes.rb
Rails.application.routes.draw do
  root 'blogs#list'
  get 'blogs/new' => 'blogs#new', as: :new_blog #new_blog_path

  get 'blogs/:id' => 'blogs#detail', as: :blog
  post 'blogs' => 'blogs#create'

  get 'blogs/:id/edit' => 'blogs#edit', as: :edit_blog
  patch 'blogs/:id' => 'blogs#update'

  delete 'blogs/:id' => 'blogs#delete'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  #validates :title :body
  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def list
    @blogs = Blog.all
  end

  def detail
    @blog = Blog.find params[:id]
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new params.require(:blog).permit(:title, :body)
    if @blog.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find params[:id]
  end

  def update
    @blog = Blog.find params[:id]
    if @blog.update params.require(:blog).permit(:title, :body)
      redirect_to root_path
    else
      render :edit
    end
  end

  def delete
    @blog = Blog.find params[:id]
    @blog.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/detail.html.erb
<div class="container">
  <h1><%= @blog.title %></h1>
  <p><%= @blog.body %></p>


  <%= link_to edit_blog_path do %>
    <button type="button" class="btn btn-default btn-md">
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit Post
    </button>
  <% end %>
  <%= link_to root_path do %>
    <button type="button" class="btn btn-default btn-md">
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
    </button>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<div class="container">
  <h1>Edit your blog post</h1>

  <%= form_for @blog  do |f| %>

    <div>
      <%= f.label :title %>
      <%= f.text_field :title %><em><%= @blog.errors[:title].join(", ") %></em>
    </div>

    <div class="body-text">
      <%= f.label :body %>
      <%= f.text_area :body %><em><%= @blog.errors[:body].join(", ") %></em>
    </div>

    <div>
      <%= f.submit %> or <%= link_to 'Delete', "/blogs/#{@blog.id}", method: :delete, data: {confirm: "Are you sure?"} %>
    </div>

  <% end %>
  <%= link_to root_path do %>
    <button type="button" class="btn btn-default btn-md">
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
    </button>
  <% end %>
</div>

app/views/blogs/list.html.erb
<div class="container">
  <h1>Your blog posts</h1>

  <ul>
    <% @blogs.each do |blog| %>
      <li><%= link_to blog.title, "/blogs/#{blog.id}" %></li>
    <% end %>
  </ul>

  <%= link_to new_blog_path do %>
    <button type="button" class="btn btn-default btn-md">
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add new post
    </button>
  <% end %>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <h1>Post a new blog</h1>

  <%= form_for @blog  do |f| %>


    <div>
      <%= f.label :title %>
      <%= f.text_field :title %><em><%= @blog.errors[:title].join(", ") %></em>
    </div>

    <div class="body-text">
      <%= f.label :body %>
      <%= f.text_area :body %><em><%= @blog.errors[:body].join(", ") %></em>
    </div>

    <div>
      <%= f.submit %>
    </div>

  <% end %>

  <%= link_to root_path do %>
    <button type="button" class="btn btn-default btn-md">
      <span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home
    </button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
      <div class="page-header header">
        <h1>Eat Your Heart Out Tumblr <small>"15-minute blog site"</small></h1>
      </div>
      <%= yield %>
    </div>

</body>
</html>